### ISSUE TITLE
MVP 버전에 대한 TODO 작성 수행

### ISSUE THREAD

**Issue by lutics** [yjung0911/coffee_order#2]
- [x] Wiki 옆의 Project 라는 메뉴에서 MVP 라는 명칭의 프로젝트를 생성한다, Desc 는 알아서 작성
- [x] Wiki 에서 작성한 내용 중 MVP 에서 만들어 낼 수 있는 기본을 추려 1일에 할 수 있을 량으로 쪼개어 작성한다

Task 2 수행 간 Wiki 를 계속 수정하면서 구현하고자 하는 목록에 대한 명세를 분명히 하는게 좋다

**Comment by lutics** [comment]
Additional Task
- [x] 우측 [Assignees] 를 눌러 본인을 이 이슈에 할당한다
- [ ] 위 2개의 Task 중 완료가 된 항목이 있다면 네모에 클릭을 해서 완료처리를 한다
